import { appendTransaction, persistStore, removeBankAccount, resetStore } from "../data/store";
import { hydrateStore } from "../data/hydrate";
import { bankLogoSrc, bankView, dashboardSnapshot, dashboardState } from "../data/view";
import {
  EXTRACT_DELAY_MS,
  SAMPLE_BILL,
  SAMPLE_BILLS,
  extractBill,
  extractDelayMs,
  extractedBillForm
} from "../data/sample-bill";
import { CONNECTED_BANKING_PREVIEW, QATAR_BANKS, SAMPLE_BANKS, SAMPLE_CHECKOUT_ANALYTICS, SAMPLE_SHOPIFY_ORDER } from "../data/sample-checkout";
import { dateInputValue, formatDate, offsetFromLabel, previousMonthLabel } from "../format";
import {
  SETTLEMENT_DELAY_MS,
  addClient,
  addSubscriber,
  cancelRecurringInvoice,
  cancelSubscriber,
  cancelSubscriptionPlan,
  checkoutPageBySlug,
  checkoutPageUnavailable,
  confirmMatch,
  connectSampleBank,
  importBankStatement,
  connectShopify,
  createInvoice,
  createPaymentLink,
  createRecurringInvoice,
  createSubscriptionPlan,
  createTag,
  deactivatePaymentLink,
  defaultPayrollPeriod,
  duplicateInvoice,
  ingestShopifyOrder,
  pauseRecurringInvoice,
  pauseSubscriber,
  paymentLinkById,
  payPublishedCheckout,
  payrollPostedFor,
  payslipsForPeriod,
  peekNextInvoiceNumber,
  generatePayslips,
  postPayroll,
  publishCheckoutPage,
  recurringNextOffsets,
  removeTag,
  renameTag,
  requestApproval,
  resolveApproval,
  runSimulatedBilling,
  saveCheckoutSettings,
  saveMerchantProfile,
  sendRecurringInvoice,
  setApprovalLimit,
  setRolePermission,
  setTagParent,
  setSmartCheckout,
  settleBilling,
  settleCheckoutPayment,
  settlePayment,
  simulatePayment,
  updateClient
} from "../data/spine";
import { exportTallyXml, simulateZohoSync } from "../data/tally-export";
import { resetGateway } from "../gateway/index";

export const FlowStore = {
  SETTLEMENT_DELAY_MS,
  appendTransaction,
  persistStore,
  removeBankAccount,
  resetStore,
  hydrateFromStorage: hydrateStore,
  dashboardState,
  dashboardSnapshot,
  bankView,
  bankLogoSrc,
  EXTRACT_DELAY_MS,
  SAMPLE_BILL,
  SAMPLE_BILLS,
  extractBill,
  extractDelayMs,
  extractedBillForm,
  SAMPLE_BANKS,
  CONNECTED_BANKING_PREVIEW,
  QATAR_BANKS,
  SAMPLE_CHECKOUT_ANALYTICS,
  SAMPLE_SHOPIFY_ORDER,
  dateInputValue,
  formatDate,
  offsetFromLabel,
  previousMonthLabel,
  addClient,
  addSubscriber,
  cancelRecurringInvoice,
  cancelSubscriber,
  cancelSubscriptionPlan,
  checkoutPageBySlug,
  checkoutPageUnavailable,
  confirmMatch,
  connectSampleBank,
  importBankStatement,
  connectShopify,
  createInvoice,
  createPaymentLink,
  createRecurringInvoice,
  createSubscriptionPlan,
  createTag,
  deactivatePaymentLink,
  defaultPayrollPeriod,
  duplicateInvoice,
  ingestShopifyOrder,
  pauseRecurringInvoice,
  pauseSubscriber,
  paymentLinkById,
  payPublishedCheckout,
  payrollPostedFor,
  payslipsForPeriod,
  peekNextInvoiceNumber,
  generatePayslips,
  postPayroll,
  publishCheckoutPage,
  recurringNextOffsets,
  removeTag,
  renameTag,
  requestApproval,
  resolveApproval,
  runSimulatedBilling,
  saveCheckoutSettings,
  saveMerchantProfile,
  sendRecurringInvoice,
  setApprovalLimit,
  setRolePermission,
  setTagParent,
  setSmartCheckout,
  settleBilling,
  settleCheckoutPayment,
  settlePayment,
  simulatePayment,
  updateClient,
  exportTallyXml,
  simulateZohoSync,
  resetGateway
};
