import { appendTransaction, resetStore } from "../data/store";
import { hydrateStore } from "../data/hydrate";
import { dashboardSnapshot, dashboardState } from "../data/view";
import {
  EXTRACT_DELAY_MS,
  SAMPLE_BILL,
  SAMPLE_BILLS,
  extractBill,
  extractDelayMs,
  extractedBillForm
} from "../data/sample-bill";
import { SAMPLE_BANKS, SAMPLE_CHECKOUT_ANALYTICS, SAMPLE_SHOPIFY_ORDER } from "../data/sample-checkout";
import { dateInputValue, formatDate, offsetFromLabel, previousMonthLabel } from "../format";
import {
  addClient,
  addSubscriber,
  cancelSubscriber,
  confirmMatch,
  connectSampleBank,
  connectShopify,
  createInvoice,
  createPaymentLink,
  createSubscriptionPlan,
  deactivatePaymentLink,
  defaultPayrollPeriod,
  duplicateInvoice,
  ingestShopifyOrder,
  pauseSubscriber,
  pauseRecurringInvoice,
  payrollPostedFor,
  postPayroll,
  publishCheckoutPage,
  removeTag,
  renameTag,
  recurringNextOffsets,
  requestApproval,
  resolveApproval,
  runSimulatedBilling,
  saveCheckoutSettings,
  sendRecurringInvoice,
  setApprovalLimit,
  setRolePermission,
  setSmartCheckout,
  settleBilling,
  settlePayment,
  simulatePayment,
  cancelRecurringInvoice,
  createRecurringInvoice
} from "../data/spine";
import { exportTallyXml, simulateZohoSync } from "../data/tally-export";
import { resetGateway } from "../gateway/index";

export const FlowStore = {
  appendTransaction,
  resetStore,
  hydrateFromStorage: hydrateStore,
  dashboardState,
  dashboardSnapshot,
  EXTRACT_DELAY_MS,
  SAMPLE_BILL,
  SAMPLE_BILLS,
  extractBill,
  extractDelayMs,
  extractedBillForm,
  SAMPLE_BANKS,
  SAMPLE_CHECKOUT_ANALYTICS,
  SAMPLE_SHOPIFY_ORDER,
  dateInputValue,
  formatDate,
  offsetFromLabel,
  previousMonthLabel,
  addClient,
  addSubscriber,
  cancelSubscriber,
  confirmMatch,
  connectSampleBank,
  connectShopify,
  createInvoice,
  createPaymentLink,
  createSubscriptionPlan,
  deactivatePaymentLink,
  defaultPayrollPeriod,
  duplicateInvoice,
  ingestShopifyOrder,
  pauseSubscriber,
  pauseRecurringInvoice,
  payrollPostedFor,
  postPayroll,
  publishCheckoutPage,
  removeTag,
  renameTag,
  recurringNextOffsets,
  requestApproval,
  resolveApproval,
  runSimulatedBilling,
  saveCheckoutSettings,
  sendRecurringInvoice,
  setApprovalLimit,
  setRolePermission,
  setSmartCheckout,
  settleBilling,
  settlePayment,
  simulatePayment,
  cancelRecurringInvoice,
  createRecurringInvoice,
  exportTallyXml,
  simulateZohoSync,
  resetGateway
};
