#!/usr/bin/env python3
"""Apply remaining dashboard UI strings to locales and view.tsx."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VIEW = ROOT / "app/dashboard/view.tsx"
EN_UI = ROOT / "locales/en/ui.json"
AR_UI = ROOT / "locales/ar/ui.json"

# Exact JSX / attribute English -> (key, ar)
# Keys are under ui.*
STRINGS: list[tuple[str, str, str]] = [
    ("Automatic Checkout", "smart.title", "الدفع التلقائي"),
    ("Runs on its own, optimising for your customers", "smart.sub", "يعمل من تلقاء نفسه، ويختار الأنسب لعملائك"),
    ("Payment methods, best first", "smart.methods", "طرق الدفع، الأفضل أولاً"),
    ("We show each customer the method they're most likely to use.", "smart.methodsSub", "نعرض لكل عميل الطريقة الأكثر احتمالاً أن يستخدمها."),
    ("Debit / credit card", "smart.card", "بطاقة مدى / ائتمان"),
    ("Detect wallets automatically", "smart.wallets", "اكتشاف المحافظ تلقائياً"),
    ("Show Apple Pay / Google Pay only when available", "smart.walletsSub", "اعرض Apple Pay / Google Pay فقط عند توفرهما"),
    ("Retry after a decline", "smart.retry", "أعد المحاولة بعد الرفض"),
    ("Offer another method without leaving the page", "smart.retrySub", "اعرض طريقة أخرى دون مغادرة الصفحة"),
    ("Where people drop off", "smart.dropoff", "أين ينسحب الناس"),
    ("Your payment gateway, money settles straight to you", "pay.gatewaySub", "بوابة الدفع الخاصة بك، والأموال تصل إليك مباشرة"),
    ("This month", "pay.thisMonth", "هذا الشهر"),
    ("Settling", "pay.settling", "قيد التسوية"),
    ("Settled share", "pay.settledShare", "نسبة المسوّى"),
    ("How your payment pages look", "pay.look", "كيف تبدو صفحات الدفع"),
    ("Applies to payment pages, links, invoices and receipts", "pay.lookSub", "ينطبق على صفحات الدفع والروابط والفواتير والإيصالات"),
    ("Logo", "pay.logo", "الشعار"),
    ("Your logo", "pay.yourLogo", "شعارك"),
    ("PNG or SVG, at least 128px square", "pay.logoHint", "PNG أو SVG، مربع بما لا يقل عن ١٢٨ بكسل"),
    ("Accent colour", "pay.accent", "لون التمييز"),
    ("Hex", "pay.hex", "سداسي"),
    ("Send a test payment", "pay.testPay", "إرسال دفعة تجريبية"),
    ("Manage connection", "pay.manageConn", "إدارة الاتصال"),
    ("Add another gateway", "pay.addGateway", "إضافة بوابة أخرى"),
    ("Run a second provider alongside SkipCash, or switch over entirely.", "pay.addGatewaySub", "شغّل مزوداً ثانياً إلى جانب SkipCash، أو انتقل إليه بالكامل."),
    ("How settlement works", "pay.howSettle", "كيف تعمل التسوية"),
    ("Your payment pages", "pay.pages", "صفحات الدفع"),
    ("New page", "pay.newPage", "صفحة جديدة"),
    ("No pages yet", "pay.noPages", "لا صفحات بعد"),
    ("Create a page customers can open, fill in and pay on.", "pay.noPagesSub", "أنشئ صفحة يفتحها العملاء ويعبئونها ويدفعون عليها."),
    ("Page published", "pay.published", "تم نشر الصفحة"),
    ("All payment pages", "pay.allPages", "كل صفحات الدفع"),
    ("Edit page", "pay.editPage", "تعديل الصفحة"),
    ("Your page is live", "pay.pageLive", "صفحتك مباشرة"),
    ("Share the link and customers can pay you straight away. Every payment lands in Money In & Out.", "pay.pageLiveSub", "شارك الرابط ويدفع لك العملاء فوراً. كل دفعة تصل إلى الأموال الداخلة والخارجة."),
    ("What happens next", "pay.next", "ماذا بعد"),
    ("Receipt settings", "pay.receipts", "إعدادات الإيصال"),
    ("Page settings", "pay.pageSettings", "إعدادات الصفحة"),
    ("You can change receipts and page settings any time from this page.", "pay.changeAnytime", "يمكنك تغيير الإيصالات وإعدادات الصفحة في أي وقت من هنا."),
    ("Receipts", "pay.receiptsShort", "الإيصالات"),
    ("Click any text to edit", "pay.clickEdit", "انقر أي نص للتعديل"),
    ("Add a goal tracker", "pay.addGoal", "إضافة متتبع هدف"),
    ("Shows a progress bar toward a target amount raised, so contributors see how close you are to the goal.", "pay.addGoalSub", "يعرض شريط تقدم نحو مبلغ مستهدف، فيرى المساهمون قربهم من الهدف."),
    ("Goal tracker", "pay.goal", "متتبع الهدف"),
    ("Shows a progress bar as payments come in", "pay.goalSub", "يعرض شريط تقدم مع ورود الدفعات"),
    ("Target", "pay.target", "الهدف"),
    ("Normal", "pay.normal", "عادي"),
    ("Heading", "pay.heading", "العنوان"),
    ("Subheading", "pay.subheading", "العنوان الفرعي"),
    ("Share this on", "pay.shareOn", "شارك هذا على"),
    ("Contact us", "pay.contact", "تواصل معنا"),
    ("Terms and conditions", "pay.terms", "الشروط والأحكام"),
    ("A short note above the pay button", "pay.noteAbove", "ملاحظة قصيرة فوق زر الدفع"),
    ("Want a payment page like this for your business?", "pay.wantPage", "تريد صفحة دفع كهذه لمنشأتك؟"),
    ("Visit", "pay.visit", "زر"),
    ("Flow Payment Pages", "pay.flowPages", "صفحات دفع فلو"),
    ("to get started.", "pay.getStarted", "للبدء."),
    ("Payment details", "pay.details", "تفاصيل الدفع"),
    ("Select amount type", "pay.amountType", "اختر نوع المبلغ"),
    ("To be filled by customer", "pay.filledBy", "يملأه العميل"),
    ("Name on checkout", "pay.nameOn", "الاسم في الدفع"),
    ("Customers type any amount on the page.", "pay.anyAmount", "يكتب العملاء أي مبلغ على الصفحة."),
    ("Customers can skip this field.", "pay.skipField", "يمكن للعملاء تخطي هذا الحقل."),
    ("Mandatory", "pay.mandatory", "إلزامي"),
    ("Required", "pay.required", "مطلوب"),
    ("Add new", "pay.addNew", "إضافة جديد"),
    ("Input field", "pay.inputField", "حقل إدخال"),
    ("Payment button label", "pay.btnLabel", "تسمية زر الدفع"),
    ("Collected via links", "links.collected", "محصّل عبر الروابط"),
    ("All time", "links.allTime", "كل الوقت"),
    ("Active links", "links.active", "روابط نشطة"),
    ("Ready to share", "links.ready", "جاهزة للمشاركة"),
    ("Times paid", "links.timesPaid", "مرات الدفع"),
    ("Across every link", "links.across", "عبر كل الروابط"),
    ("Payment Links", "links.title", "روابط الدفع"),
    ("New link", "links.new", "رابط جديد"),
    ("DESCRIPTION", "col.description", "الوصف"),
    ("AMOUNT", "col.amount", "المبلغ"),
    ("STATUS", "col.status", "الحالة"),
    ("CREATED", "col.created", "أُنشئ"),
    ("USES", "col.uses", "الاستخدام"),
    ("No links yet", "links.empty", "لا روابط بعد"),
    ("Create a link and send it so someone can pay you.", "links.emptySub", "أنشئ رابطاً وأرسله ليدفع لك أحدهم."),
    ("Subscription plans", "subs.plans", "خطط الاشتراك"),
    ("New plan", "subs.new", "خطة جديدة"),
    ("Recurring revenue", "subs.mrr", "إيراد متكرر"),
    ("Every month, before fees", "subs.mrrSub", "كل شهر، قبل الرسوم"),
    ("Active subscribers", "subs.active", "مشتركون نشطون"),
    ("Average per customer", "subs.avg", "المتوسط لكل عميل"),
    ("Monthly, all plans", "subs.avgSub", "شهرياً، كل الخطط"),
    ("Plan", "subs.plan", "الخطة"),
    ("Price", "subs.price", "السعر"),
    ("Subscribers", "subs.people", "المشتركون"),
    ("Monthly revenue", "subs.rev", "الإيراد الشهري"),
    ("No plans yet", "subs.empty", "لا خطط بعد"),
    ("Create a plan and customers can pay you every month.", "subs.emptySub", "أنشئ خطة ويدفع لك العملاء كل شهر."),
    ("Bank activity", "bank.activity", "نشاط البنك"),
    ("Sample data. Live bank feeds arrive in a later phase.", "bank.sample", "بيانات تجريبية. التغذية البنكية المباشرة تأتي في مرحلة لاحقة."),
    ("Need another bank account?", "bank.needAnother", "تحتاج حساباً بنكياً آخر؟"),
    ("Connect another bank", "bank.connectAnother", "ربط بنك آخر"),
    ("All sample banks in this sandbox are connected.", "bank.allConnected", "كل البنوك التجريبية في هذه البيئة متصلة."),
    ("Sample banks only. Live QCB feeds need Express Sandbox admission.", "bank.sampleOnly", "بنوك تجريبية فقط. تغذية مصرف قطر المركزي تحتاج قبول Express Sandbox."),
    ("This connection is labelled sample data. It does not change cash on hand.", "bank.consent", "هذا الاتصال معلّم كبيانات تجريبية. لا يغيّر النقد المتوفر."),
    ("Connect sample bank", "bank.connectSample", "ربط بنك تجريبي"),
    ("Store URL", "shop.url", "رابط المتجر"),
    ("Connect Shopify", "shop.connect", "ربط شوبيفاي"),
    ("Approve access", "shop.approve", "الموافقة على الوصول"),
    ("Checkout maps to", "shop.maps", "الدفع يقابل"),
    ("Currency", "shop.currency", "العملة"),
    ("Sync products", "shop.syncProducts", "مزامنة المنتجات"),
    ("Keep names and prices in step", "shop.syncProductsSub", "أبقِ الأسماء والأسعار متوافقة"),
    ("Test mode", "shop.test", "وضع الاختبار"),
    ("Orders are recorded but not charged", "shop.testSub", "تُسجَّل الطلبات دون تحصيل"),
    ("Pull sample order", "shop.sampleOrder", "سحب طلب تجريبي"),
    ("Sync status", "shop.syncStatus", "حالة المزامنة"),
    ("Plugin", "shop.plugin", "الإضافة"),
    ("Orders on ledger", "shop.orders", "طلبات في الدفتر"),
    ("Setup guide", "shop.guide", "دليل الإعداد"),
    ("Install the Flow app from the Shopify app store", "shop.step1", "ثبّت تطبيق فلو من متجر تطبيقات شوبيفاي"),
    ("Approve access to orders and products", "shop.step2", "وافق على الوصول إلى الطلبات والمنتجات"),
    ("Choose Flow checkout at the payments step", "shop.step3", "اختر دفع فلو في خطوة المدفوعات"),
    ("All transactions", "txn.all", "كل الحركات"),
    ("Counterparty", "txn.party", "الطرف"),
    ("No transactions match these filters", "txn.empty", "لا حركات تطابق هذه العوامل"),
    ("Widen the period or clear a filter to see more.", "txn.emptySub", "وسّع الفترة أو امسح عاملاً لترى المزيد."),
    ("See payment activity", "txn.seePay", "عرض نشاط الدفع"),
    ("Match rate this month", "match.rate", "نسبة المطابقة هذا الشهر"),
    ("Matched automatically", "match.auto", "مطابقة تلقائية"),
    ("No action needed", "match.noAction", "لا إجراء مطلوب"),
    ("Take a photo of the bill", "scan.title", "صوّر الفاتورة"),
    ("Or drop a PDF, we'll read the details for you", "scan.sub", "أو أفلت ملفاً PDF، نقرأ التفاصيل لك"),
    ("Upload a bill", "scan.upload", "رفع فاتورة"),
    ("What we pull out", "scan.pull", "ما نستخرجه"),
    ("Vendor", "scan.vendor", "المورّد"),
    ("Blurry photo? We'll flag it for manual entry instead of guessing.", "scan.blur", "صورة غير واضحة؟ نوسّمها للإدخال اليدوي بدل التخمين."),
    ("Sample data, not a live feed", "bankfeed.sample", "بيانات تجريبية، ليست تغذية مباشرة"),
    ("Bank side by side with Flow", "bankfeed.side", "البنك جنباً إلى جنب مع فلو"),
    ("New invoice", "inv.new", "فاتورة جديدة"),
    ("Address", "inv.address", "العنوان"),
    ("Billing address (optional)", "inv.billAddr", "عنوان الفوترة (اختياري)"),
    ("PO / Reference (optional)", "inv.po", "أمر شراء / مرجع (اختياري)"),
    ("Line items", "inv.lines", "البنود"),
    ("QTY", "inv.qty", "الكمية"),
    ("PRICE", "inv.price", "السعر"),
    ("TOTAL", "inv.total", "الإجمالي"),
    ("+ Add line item", "inv.addLine", "+ إضافة بند"),
    ("Issue date", "inv.issue", "تاريخ الإصدار"),
    ("Due date", "inv.due", "تاريخ الاستحقاق"),
    ("Tax %", "inv.tax", "الضريبة ٪"),
    ("Discount (optional)", "inv.discount", "خصم (اختياري)"),
    ("Partial payment", "inv.partial", "دفع جزئي"),
    ("Allow the customer to pay less than the full amount", "inv.partialSub", "اسمح للعميل بدفع أقل من المبلغ الكامل"),
    ("Attachments (optional)", "inv.attach", "مرفقات (اختياري)"),
    ("Attach files", "inv.attachFiles", "إرفاق ملفات"),
    ("Notes", "inv.notes", "ملاحظات"),
    ("Terms & conditions (optional)", "inv.terms", "الشروط والأحكام (اختياري)"),
    ("Create invoice", "inv.create", "إنشاء فاتورة"),
    ("Save as draft", "inv.draft", "حفظ كمسودة"),
    ("Copy invoice link", "inv.copyLink", "نسخ رابط الفاتورة"),
    ("Outstanding", "inv.outstanding", "المستحقات"),
    ("Total invoiced", "inv.totalInv", "إجمالي المفوتر"),
    ("Overdue", "inv.overdue", "متأخر"),
    ("All Invoices", "inv.all", "كل الفواتير"),
    ("Send reminders", "inv.sendRem", "إرسال تذكيرات"),
    ("NUMBER", "col.number", "الرقم"),
    ("CLIENT", "col.client", "العميل"),
    ("DUE", "col.due", "الاستحقاق"),
    ("TAG", "col.tag", "الوسم"),
    ("No invoices yet", "inv.empty", "لا فواتير بعد"),
    ("Bill a client and Flow will track what is paid and what is late.", "inv.emptySub", "فوتر عميلاً وسيتبع فلو المدفوع والمتأخر."),
    ("No invoices match these filters", "inv.emptyFilt", "لا فواتير تطابق هذه العوامل"),
    ("Make this invoice recurring", "rec.title", "اجعل هذه الفاتورة متكررة"),
    ("Flow sends it for you on a schedule", "rec.sub", "يرسلها فلو نيابة عنك وفق جدول"),
    ("Every", "rec.every", "كل"),
    ("Ends", "rec.ends", "تنتهي"),
    ("Start schedule", "rec.start", "بدء الجدول"),
    ("NEXT THREE SENDS", "rec.next3", "الإرسالات الثلاث التالية"),
    ("No recurring invoices are stored.", "rec.noneStored", "لا فواتير متكررة مخزّنة."),
    ("Running now", "rec.running", "تعمل الآن"),
    ("Send now", "rec.sendNow", "أرسل الآن"),
    ("Pause", "rec.pause", "إيقاف مؤقت"),
    ("Nothing is running on a schedule.", "rec.noneRun", "لا شيء يعمل وفق جدول."),
    ("When we nudge clients", "rem.when", "متى ننبّه العملاء"),
    ("Send one now", "rem.sendNow", "أرسل واحداً الآن"),
    ("Nothing to remind right now", "rem.empty", "لا شيء للتذكير الآن"),
    ("Reminders go to invoices that are sent, viewed, overdue or awaiting settlement.", "rem.emptySub", "التذكيرات تذهب للفواتير المرسلة أو المشاهدة أو المتأخرة أو بانتظار التسوية."),
    ("Remind", "rem.cta", "ذكّر"),
    ("Lifetime", "cli.life", "مدى التعامل"),
    ("Invoices", "cli.invoices", "الفواتير"),
    ("Sync automatically", "acc.auto", "مزامنة تلقائية"),
    ("Every day at 06:00", "acc.daily", "كل يوم الساعة ٠٦:٠٠"),
    ("Sync now", "acc.now", "زامن الآن"),
    ("Disconnect", "acc.disc", "قطع الاتصال"),
    ("Sync log", "acc.log", "سجل المزامنة"),
    ("See sync activity", "acc.see", "عرض نشاط المزامنة"),
    ("Export for Tally", "tally.title", "تصدير لتالي"),
    ("Download an XML file and import it into Tally. Two-way live sync needs a desktop connector, that comes later.", "tally.sub", "نزّل ملف XML واستورده إلى تالي. المزامنة المباشرة باتجاهين تحتاج موصلاً مكتبياً، يأتي لاحقاً."),
    ("From", "tally.from", "من"),
    ("To", "tally.to", "إلى"),
    ("Export XML", "tally.xml", "تصدير XML"),
    ("Export history", "tally.hist", "سجل التصدير"),
    ("No export history is stored.", "tally.noHist", "لا سجل تصدير مخزّناً."),
    ("Tax", "tax.title", "الضريبة"),
    ("Not registered for this merchant", "tax.none", "غير مسجّل لهذه المنشأة"),
    ("This merchant is not registered. Qatar commercial invoices do not add a goods-and-services tax line.", "tax.body", "هذه المنشأة غير مسجّلة. الفواتير التجارية القطرية لا تضيف بند ضريبة سلع وخدمات."),
    ("Tax registration number", "tax.reg", "رقم التسجيل الضريبي"),
    ("Active connections", "conn.active", "اتصالات نشطة"),
    ("Needs attention", "conn.needs", "يحتاج انتباهاً"),
    ("Last check", "conn.last", "آخر فحص"),
    ("Today", "conn.today", "اليوم"),
    ("Sandbox keys · last event 12 minutes ago", "conn.keys", "مفاتيح تجريبية · آخر حدث قبل ١٢ دقيقة"),
    ("One simulated gateway in this phase. These are on the roadmap.", "conn.oneGw", "بوابة تجريبية واحدة في هذه المرحلة. هذه على خارطة الطريق."),
    ("Coming soon", "conn.soon", "قريباً"),
    ("File export", "conn.file", "تصدير ملف"),
    ("Last sync today, 06:00", "conn.lastSync", "آخر مزامنة اليوم، ٠٦:٠٠"),
    ("Net profit", "rep.net", "صافي الربح"),
    ("CASH ON HAND", "rep.cash", "النقد المتوفر"),
    ("RUNWAY", "rep.runway", "المدرج"),
    ("Solid bars are actual, outlined bars are projected", "rep.bars", "الأشرطة المصمتة فعلية، والمحددة متوقعة"),
    ("In", "rep.in", "داخل"),
    ("Out", "rep.out", "خارج"),
    ("Where money went", "rep.spend", "أين ذهبت الأموال"),
    ("Refunds", "rep.refunds", "المستردات"),
    ("Not counted as spend", "rep.notSpend", "لا تُحتسب إنفاقاً"),
    ("Biggest vendors", "rep.vendors", "أكبر المورّدين"),
    ("Who owes you", "rep.owes", "من يدين لك"),
    ("Chase all overdue", "rep.chase", "مطالبة كل المتأخر"),
    ("Accountant pack", "rep.pack", "حزمة المحاسب"),
    ("One download with everything your accountant asks for, structured and ready to file.", "rep.packSub", "تنزيل واحد بكل ما يطلبه محاسبك، منظّماً وجاهزاً للتقديم."),
    ("Format", "rep.format", "الصيغة"),
    ("Download pack", "rep.dlPack", "تنزيل الحزمة"),
    ("Saved reports", "rep.saved", "تقارير محفوظة"),
    ("Packs you download are saved here for 12 months.", "rep.savedSub", "الحزم التي تنزّلها تُحفظ هنا لمدة ١٢ شهراً."),
    ("Send it monthly", "rep.monthly", "أرسله شهرياً"),
    ("Turn on monthly send", "rep.monthlyOn", "تفعيل الإرسال الشهري"),
    ("Branch performance", "rep.branch", "أداء الفروع"),
    ("BRANCH", "col.branch", "الفرع"),
    ("REVENUE", "col.revenue", "الإيراد"),
    ("SHARE", "col.share", "الحصة"),
    ("PEOPLE", "col.people", "الأشخاص"),
    ("People with access", "team.people", "من لديهم وصول"),
    ("Invite", "team.invite", "دعوة"),
    ("Person", "team.person", "الشخص"),
    ("Last active", "team.last", "آخر نشاط"),
    ("Only you have access", "team.onlyYou", "أنت وحدك من لديه وصول"),
    ("Invite your accountant or a staff member and set what they can reach.", "team.onlyYouSub", "ادعُ محاسبك أو موظفاً وحدّد ما يمكنهم الوصول إليه."),
    ("Invite someone", "team.inviteSomeone", "ادعُ شخصاً"),
    ("What each role can reach", "perm.title", "ما يصل إليه كل دور"),
    ("Pick a level for each role", "perm.sub", "اختر مستوى لكل دور"),
    ("AREA", "col.area", "المجال"),
    ("OWNER", "col.owner", "المالك"),
    ("ACCOUNTANT", "col.accountant", "المحاسب"),
    ("STAFF", "col.staff", "موظف"),
    ("Approval limits", "appr.title", "حدود الاعتماد"),
    ("Anything above a person's limit waits for the owner to approve.", "appr.sub", "أي شيء فوق حد الشخص ينتظر موافقة المالك."),
    ("Waiting on you", "appr.wait", "بانتظارك"),
    ("Nothing to approve", "appr.empty", "لا شيء للاعتماد"),
    ("Requests over a limit will show up here.", "appr.emptySub", "الطلبات فوق الحد تظهر هنا."),
    ("Activity", "audit.title", "النشاط"),
    ("TYPE", "col.type", "النوع"),
    ("Nothing recorded under this type yet.", "audit.empty", "لا شيء مسجلاً تحت هذا النوع بعد."),
    ("When", "audit.when", "متى"),
    ("Who", "audit.who", "من"),
    ("What happened", "audit.what", "ماذا حدث"),
    ("Type", "audit.type", "النوع"),
    ("Employees", "payr.emps", "الموظفون"),
    ("Add employee", "payr.add", "إضافة موظف"),
    ("Monthly", "payr.monthly", "شهري"),
    ("Paid by", "payr.paidBy", "يُدفع عبر"),
    ("Nobody on payroll yet", "payr.empty", "لا أحد على كشف الرواتب بعد"),
    ("Add an employee and Flow works out deductions and payslips for you.", "payr.emptySub", "أضف موظفاً ويحسب فلو الاستقطاعات والكشوف لك."),
    ("Monthly payroll", "payr.month", "الرواتب الشهرية"),
    ("Before deductions", "payr.before", "قبل الاستقطاعات"),
    ("Net to pay", "payr.net", "صافي المستحق"),
    ("On payroll", "payr.on", "على الكشف"),
    ("Active employees", "payr.active", "موظفون نشطون"),
    ("Send payroll to Transactions", "payr.send", "إرسال الرواتب إلى الحركات"),
    ("Adds one expense line tagged Salaries, ready for your books.", "payr.sendSub", "يضيف بند مصروف بوسم الرواتب، جاهزاً لدفاترك."),
    ("Generate payslips", "payr.gen", "إنشاء الكشوف"),
    ("Generate", "payr.genCta", "إنشاء"),
    ("Breakdown preview", "payr.break", "معاينة التفصيل"),
    ("Base salaries", "payr.base", "الرواتب الأساسية"),
    ("Deductions", "payr.ded", "الاستقطاعات"),
    ("Qatar rates in use", "payr.rates", "أسعار قطر المستخدمة"),
    ("Change a rate and every payroll figure follows", "payr.ratesSub", "غيّر سعراً وتتبعه كل أرقام الرواتب"),
    ("Withholding, services", "payr.whSvc", "استقطاع، خدمات"),
    ("Applied to salaries and service invoices", "payr.whSvcSub", "يُطبَّق على الرواتب وفواتير الخدمات"),
    ("Withholding, royalties", "payr.whRoy", "استقطاع، إتاوات"),
    ("Applied to royalty payments", "payr.whRoySub", "يُطبَّق على دفعات الإتاوات"),
    ("Save rates", "payr.saveRates", "حفظ الأسعار"),
    ("This period", "payr.period", "هذه الفترة"),
    ("Payroll base", "payr.base2", "أساس الرواتب"),
    ("Withholding due", "payr.whDue", "الاستقطاع المستحق"),
    ("These are indicative figures for your records, confirm with your accountant before filing.", "payr.disclaimer", "هذه أرقام إرشادية لسجلاتك، أكّدها مع محاسبك قبل التقديم."),
    ("DATE", "col.date", "التاريخ"),
    ("SOURCE", "col.source", "المصدر"),
    ("MATCHED", "col.matched", "مطابق"),
    ("What happened to this payment", "det.whatPay", "ماذا حدث لهذه الدفعة"),
    ("No activity is stored for this payment.", "det.noAct", "لا نشاط مخزناً لهذه الدفعة."),
    ("Send reminder", "det.remind", "إرسال تذكير"),
    ("Duplicate", "det.dup", "تكرار"),
    ("Void", "det.void", "إلغاء"),
    ("Status timeline", "det.timeline", "الجدول الزمني للحالة"),
    ("Created", "det.created", "أُنشئت"),
    ("Sent to client", "det.sent", "أُرسلت للعميل"),
    ("Viewed", "det.viewed", "شوهدت"),
    ("Paid", "det.paid", "مدفوعة"),
    ("Reminders sent", "det.rems", "تذكيرات أُرسلت"),
    ("3 days before due, sent 2 Aug", "det.rem1", "قبل الاستحقاق بثلاثة أيام، أُرسل في ٢ أغسطس"),
    ("On due date, scheduled", "det.rem2", "في تاريخ الاستحقاق، مجدول"),
    ("SIMULATE PAYMENT", "det.sim", "محاكاة الدفع"),
    ("Success", "det.success", "نجاح"),
    ("Timeout", "det.timeout", "انتهاء المهلة"),
    ("Partial", "det.partial", "جزئي"),
    ("EXPIRES", "col.expires", "ينتهي"),
    ("TIMES PAID", "col.timesPaid", "مرات الدفع"),
    ("ACTIONS", "col.actions", "إجراءات"),
    ("Deactivate", "det.off", "إيقاف"),
    ("SUBSCRIBERS", "col.subs", "المشتركون"),
    ("MONTHLY REVENUE", "col.mrr", "الإيراد الشهري"),
    ("Signup link", "det.signup", "رابط الاشتراك"),
    ("UPCOMING CHARGES", "det.upcoming", "رسوم قادمة"),
    ("Run billing", "det.runBill", "تشغيل الفوترة"),
    ("Add subscriber", "det.addSub", "إضافة مشترك"),
    ("No one has subscribed yet", "det.noSub", "لم يشترك أحد بعد"),
    ("Share the signup link above and subscribers appear here.", "det.noSubSub", "شارك رابط الاشتراك أعلاه ويظهر المشتركون هنا."),
    ("SUBSCRIBER SINCE", "det.since", "مشترك منذ"),
    ("NEXT CHARGE", "det.nextCh", "الرسوم التالية"),
    ("Billing history", "det.billHist", "سجل الفوترة"),
    ("No charge history is stored.", "det.noCh", "لا سجل رسوم مخزناً."),
    ("Cancel subscription", "det.cancelSub", "إلغاء الاشتراك"),
    ("MONEY THAT ARRIVED", "det.arrived", "المال الذي وصل"),
    ("Settled via SkipCash", "det.viaSc", "سُوّي عبر SkipCash"),
    ("INVOICE WE THINK IT'S FOR", "det.thinkInv", "الفاتورة التي نظنها"),
    ("Due earlier this month", "det.dueEarlier", "استحقت في وقت أسبق هذا الشهر"),
    ("Why we matched these", "det.why", "لماذا طابقنا هذين"),
    ("Confirm match", "det.confirm", "تأكيد المطابقة"),
    ("Link to another invoice", "det.linkOther", "ربط بفاتورة أخرى"),
    ("Not a match", "det.notMatch", "ليست مطابقة"),
    ("Matched automatically, no action needed.", "det.autoOk", "مطابقة تلقائية، لا إجراء مطلوب."),
    ("Undo match", "det.undo", "التراجع عن المطابقة"),
    ("Pick an invoice", "det.pickInv", "اختر فاتورة"),
    ("EMAIL", "col.email", "البريد"),
    ("PHONE", "col.phone", "الهاتف"),
    ("LIFETIME", "col.life", "مدى التعامل"),
    ("ADDRESS", "col.address", "العنوان"),
    ("Their invoices", "det.theirInv", "فواتيرهم"),
    ("ITEMS PUSHED", "col.items", "عناصر دُفعت"),
    ("ERRORS", "col.errors", "أخطاء"),
    ("Line by line", "det.lines", "سطراً بسطر"),
    ("No sync payload is stored.", "det.noSync", "لا حمولة مزامنة مخزّنة."),
    ("Simulated connection", "det.simConn", "اتصال تجريبي"),
    ("PUBLISHABLE KEY", "col.pk", "المفتاح العام"),
    ("WEBHOOK URL", "col.hook", "رابط الويب هوك"),
    ("VOLUME (30D)", "col.vol", "الحجم (٣٠ي)"),
    ("SETTLED SHARE", "col.settled", "نسبة المسوّى"),
    ("Send test payment", "det.testPay", "إرسال دفعة تجريبية"),
    ("Re-run", "det.rerun", "إعادة التشغيل"),
    ("Owner", "role.owner", "المالك"),
    ("Manager", "role.manager", "المدير"),
    ("Accountant", "role.accountant", "المحاسب"),
    ("Staff", "role.staff", "موظف"),
    ("What they can do", "mem.can", "ما يمكنهم فعله"),
    ("See all transactions and reports", "mem.see", "رؤية كل الحركات والتقارير"),
    ("Create and send invoices", "mem.inv", "إنشاء الفواتير وإرسالها"),
    ("Change connections or billing", "mem.bill", "تغيير الاتصالات أو الفوترة"),
    ("Recent activity", "mem.recent", "النشاط الأخير"),
    ("Deactivate access", "mem.off", "إيقاف الوصول"),
    ("Revenue YTD", "br.ytd", "إيراد السنة حتى اليوم"),
    ("Share of group", "br.share", "حصة المجموعة"),
    ("People", "br.people", "الأشخاص"),
    ("Per person", "br.per", "لكل شخص"),
    ("Roll this branch into the main view", "br.roll", "دمج هذا الفرع في العرض الرئيسي"),
    ("Off means it keeps its own ledger", "br.rollSub", "إيقاف يعني أنه يحتفظ بدفتره الخاص"),
    ("How it compares", "br.compare", "كيف يقارن"),
    ("Revenue year to date, all branches", "br.compareSub", "إيراد السنة حتى اليوم، كل الفروع"),
    ("Recent activity here", "br.recent", "النشاط الأخير هنا"),
    ("MONTHLY SALARY", "col.salary", "الراتب الشهري"),
    ("DEDUCTIONS", "col.ded", "الاستقطاعات"),
    ("NET", "col.net", "الصافي"),
    ("Payslips", "emp.slips", "الكشوف"),
    ("More", "nav.more", "المزيد"),
    ("Link for this page", "ps.link", "رابط هذه الصفحة"),
    ("Page theme", "ps.theme", "مظهر الصفحة"),
    ("Light", "ps.light", "فاتح"),
    ("White page, dark pay button", "ps.lightSub", "صفحة بيضاء، زر دفع داكن"),
    ("Dark", "ps.dark", "داكن"),
    ("Dark page, light pay button", "ps.darkSub", "صفحة داكنة، زر دفع فاتح"),
    ("When the page stops accepting payments", "ps.stop", "متى تتوقف الصفحة عن قبول الدفع"),
    ("Never", "ps.never", "أبداً"),
    ("The page stays open until you close it", "ps.neverSub", "تبقى الصفحة مفتوحة حتى تغلقها"),
    ("On a date", "ps.date", "في تاريخ"),
    ("Useful for events and pre-orders", "ps.dateSub", "مفيد للفعاليات والطلبات المسبقة"),
    ("After a successful payment", "ps.after", "بعد دفعة ناجحة"),
    ("Show a thank-you message", "ps.thanks", "اعرض رسالة شكر"),
    ("The customer stays on the page", "ps.thanksSub", "يبقى العميل على الصفحة"),
    ("Send them to your website", "ps.redirect", "أرسلهم إلى موقعك"),
    ("They are redirected once payment clears", "ps.redirectSub", "يُحوَّلون بعد اكتمال الدفع"),
    ("Sending receipts", "rc.title", "إرسال الإيصالات"),
    ("Send automatically", "rc.auto", "إرسال تلقائي"),
    ("Emailed to the customer the moment payment clears", "rc.autoSub", "يُرسل بالبريد للعميل لحظة اكتمال الدفع"),
    ("Send them myself", "rc.manual", "أرسلها بنفسي"),
    ("You send receipts later from Transactions, and can add your own reference", "rc.manualSub", "ترسل الإيصالات لاحقاً من الحركات، ويمكنك إضافة مرجعك"),
    ("What the receipt shows", "rc.shows", "ما يظهره الإيصال"),
    ("Customer details", "rc.cust", "بيانات العميل"),
    ("Name, email and phone appear on the receipt", "rc.custSub", "الاسم والبريد والهاتف تظهر على الإيصال"),
    ("Your reference number", "rc.ref", "رقم مرجعك"),
    ("Adds your own order or job number", "rc.refSub", "يضيف رقم طلبك أو عملك"),
    ("Reading the bill…", "scan.read", "جارٍ قراءة الفاتورة…"),
    ("Extracting vendor, date, total, tax and line items", "scan.extract", "استخراج المورّد والتاريخ والإجمالي والضريبة والبنود"),
    ("Drop a bill photo or PDF here", "scan.drop", "أفلت صورة فاتورة أو PDF هنا"),
    ("or use your camera", "scan.camera", "أو استخدم كاميرتك"),
    ("Choose image or PDF", "scan.choose", "اختر صورة أو PDF"),
    ("FIELDS WE READ, EDIT ANYTHING", "scan.fields", "الحقول التي قرأناها، عدّل أي شيء"),
    ("Paid to", "exp.to", "مدفوع إلى"),
    ("A payment link is created automatically and attached to this invoice.", "mod.invLink", "يُنشأ رابط دفع تلقائياً ويُرفق بهذه الفاتورة."),
    ("Plan name", "mod.planName", "اسم الخطة"),
    ("Bills every", "mod.billsEvery", "تُفوتر كل"),
    ("Customer", "mod.customer", "العميل"),
    ("What subscribers get", "mod.subsGet", "ما يحصل عليه المشتركون"),
    ("A signup link is created automatically. Share it and customers subscribe themselves.", "mod.signupAuto", "يُنشأ رابط اشتراك تلقائياً. شاركه ويشترك العملاء بأنفسهم."),
    ("Full name", "mod.fullName", "الاسم الكامل"),
    ("Monthly salary", "mod.salary", "الراتب الشهري"),
    ("Payouts are manual for now, Flow records the payslip and the expense, you make the transfer.", "mod.payouts", "التحويلات يدوية حالياً، يسجّل فلو الكشف والمصروف، وأنت تنفّذ التحويل."),
    ("Simulated: SkipCash, Ahli Bank, Zoho Books, Shopify. Anything marked “Coming soon” is a later phase.", "mod.help", "تجريبي: SkipCash وبنك الأهلي وزوهو بوكس وشوبيفاي. أي شيء معلّم «قريباً» مرحلة لاحقة."),
]

ATTRS: list[tuple[str, str, str, str]] = [
    # attr, english, key, ar
    ("placeholder", "Search", "ph.search", "بحث"),
    ("placeholder", "Search payments, invoices, clients", "ph.searchAll", "ابحث في المدفوعات والفواتير والعملاء"),
    ("placeholder", "Enter page title here", "ph.pageTitle", "أدخل عنوان الصفحة هنا"),
    ("placeholder", "Tell customers what they are paying for", "ph.pageDesc", "أخبر العملاء عمّا يدفعون لأجله"),
    ("placeholder", "Support email", "ph.supportEmail", "بريد الدعم"),
    ("placeholder", "Support phone", "ph.supportPhone", "هاتف الدعم"),
    ("placeholder", "Field label", "ph.fieldLabel", "تسمية الحقل"),
    ("placeholder", "Pay", "ph.pay", "ادفع"),
    ("placeholder", "Add a new client", "ph.newClient", "إضافة عميل جديد"),
    ("placeholder", "Street, city, country", "ph.street", "الشارع، المدينة، الدولة"),
    ("placeholder", "What are you billing for", "ph.billingFor", "عمّا تفوتر"),
    ("placeholder", "Thanks for your business.", "ph.thanks", "شكراً لتعاملك معنا."),
    ("placeholder", "Payment due within 14 days of issue.", "ph.due14", "الدفع خلال ١٤ يوماً من الإصدار."),
    ("placeholder", "Search client or invoice", "ph.searchCliInv", "ابحث عن عميل أو فاتورة"),
    ("placeholder", "Select or add a client", "ph.selectClient", "اختر عميلاً أو أضفه"),
    ("placeholder", "After how many sends", "ph.afterSends", "بعد كم إرسالاً"),
    ("placeholder", "Vendor name", "ph.vendor", "اسم المورّد"),
    ("placeholder", "e.g. Monthly Care", "ph.monthlyCare", "مثال: عناية شهرية"),
    ("placeholder", "Optional first subscriber", "ph.firstSub", "أول مشترك اختياري"),
    ("placeholder", "Shown on the signup page", "ph.signupShown", "يظهر في صفحة الاشتراك"),
    ("placeholder", "https://desertbloom.qa/thank-you", "ph.thanksUrl", "https://desertbloom.qa/thank-you"),
    ("title", "More colours", "tip.moreColours", "مزيد من الألوان"),
    ("title", "Search", "tip.search", "بحث"),
    ("title", "Drag to reorder", "tip.drag", "اسحب لإعادة الترتيب"),
    ("title", "Edit field", "tip.editField", "تعديل الحقل"),
    ("title", "Customers choose the quantity", "tip.qty", "يختار العملاء الكمية"),
    ("title", "Copy signup link", "tip.copySignup", "نسخ رابط الاشتراك"),
    ("title", "Remove line", "tip.removeLine", "حذف البند"),
    ("data-note", "Logo upload is sample-only in this sandbox", "note.logo", "رفع الشعار تجريبي في هذه البيئة"),
    ("data-note", "Reminders queued for open invoices", "note.remOpen", "تم وضع تذكيرات للفواتير المفتوحة في قائمة الانتظار"),
    ("data-note", "Disconnect is sample-only in this sandbox", "note.disc", "قطع الاتصال تجريبي في هذه البيئة"),
    ("data-note", "Reminders queued for overdue invoices", "note.remOver", "تم وضع تذكيرات للفواتير المتأخرة في قائمة الانتظار"),
    ("data-note", "Signed out of iPhone 15", "note.signIphone", "تم تسجيل الخروج من iPhone 15"),
    ("data-note", "Keys rolled. Update your gateway", "note.keys", "تم تدوير المفاتيح. حدّث بوابتك"),
    ("data-note", "Downgrade is sample-only in this sandbox", "note.down", "التخفيض تجريبي في هذه البيئة"),
    ("data-note", "Upgrade is sample-only in this sandbox", "note.up", "الترقية تجريبية في هذه البيئة"),
    ("data-note", "Sales request noted", "note.sales", "تم تسجيل طلب المبيعات"),
    ("data-note", "Download queued", "note.dl", "التنزيل في قائمة الانتظار"),
]


def nest(pairs: list[tuple[str, str]]) -> dict:
    out: dict = {}
    for key, val in pairs:
        cur = out
        parts = key.split(".")
        for p in parts[:-1]:
            cur = cur.setdefault(p, {})
        cur[parts[-1]] = val
    return out


def main() -> None:
    text = VIEW.read_text()
    en_pairs = [(k, en) for en, k, _ in STRINGS]
    ar_pairs = [(k, ar) for _, k, ar in STRINGS]
    for _attr, en, k, ar in ATTRS:
        en_pairs.append((k, en))
        ar_pairs.append((k, ar))
    EN_UI.write_text(json.dumps(nest(en_pairs), ensure_ascii=False, indent=2) + "\n")
    AR_UI.write_text(json.dumps(nest(ar_pairs), ensure_ascii=False, indent=2) + "\n")

    common = {
        "Simulated": "pages.common.simulated",
        "Sandbox": "pages.common.sandbox",
        "Live": "pages.common.live",
        "Connected": "pages.common.connected",
        "Not connected": "pages.common.notConnected",
        "Coming soon": "pages.common.comingSoon",
        "Manage": "pages.common.manage",
        "Amount": "pages.common.amount",
        "Amount (QR)": "pages.common.amountQr",
        "Client": "pages.common.client",
        "Cancel": "pages.common.cancel",
        "Save": "pages.common.save",
        "Export": "pages.common.export",
        "Clear filters": "pages.common.clearFilters",
        "Copy": "pages.common.copy",
        "Share": "pages.common.share",
        "Copy link": "pages.common.copyLink",
        "Remove": "pages.common.remove",
        "Edit": "pages.common.edit",
        "Print": "pages.common.print",
        "Download": "pages.common.download",
        "Approve": "pages.common.approve",
        "Decline": "pages.common.decline",
        "Review": "pages.common.review",
        "Upload": "pages.common.upload",
        "Invite": "pages.common.invite",
        "Role": "pages.common.role",
        "Name": "pages.common.name",
        "Email": "pages.common.email",
        "Date": "pages.common.date",
        "Status": "pages.common.status",
        "Source": "pages.common.source",
        "Tag": "pages.common.tag",
        "Period": "pages.common.period",
        "Week": "pages.common.week",
        "Month": "pages.common.month",
        "Quarter": "pages.common.quarter",
        "Year": "pages.common.year",
        "Draft": "pages.status.Draft",
        "New invoice": "ui.inv.new",
    }

    def repl_text(src: str, english: str, key: str) -> str:
        token = "{v.t(\"" + key + "\")}"
        return src.replace(">" + english + "<", ">" + token + "<")

    for en, key in common.items():
        text = repl_text(text, en, key)
    for en, key, _ar in STRINGS:
        text = repl_text(text, en, "ui." + key)

    # HTML entity variant of one published-page sentence
    text = text.replace(
        "Share the link and customers can pay you straight away. Every payment lands in Money In &amp; Out.",
        "{v.t(\"ui.pay.pageLiveSub\")}",
    )

    for attr, en, key, _ar in ATTRS:
        old = f'{attr}="{en}"'
        new = f'{attr}={{v.t("ui.{key}")}}'
        text = text.replace(old, new)

    # Status chips: keep identity numbers, translate labels
    text = re.sub(
        r"\{([a-zA-Z][a-zA-Z0-9_.]*)\.status\}",
        r"{v.statusText(\1.status)}",
        text,
    )

    VIEW.write_text(text)
    print("wrote", EN_UI, AR_UI, "patched view", VIEW)


if __name__ == "__main__":
    main()
